### 1. Registrar um novo usuário (AUTOR)
POST http://localhost:8080/registrar
Content-Type: application/json

{
  "email": "autor@email.com",
  "senha": "123456"
}

### 2. Efetuar Login
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "autor@email.com",
  "senha": "123456"
}

### 3. Criar um Artigo (Autenticado)
POST http://localhost:8080/artigos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBUEkgQmxvZ0FydGlnb3MiLCJzdWIiOiJhdXRvckBlbWFpbC5jb20iLCJpZCI6IlVTUi0wMDAxIiwiZXhwIjoxNzYzMjU0NDY2fQ.B1Ke14o1RQFsadAfMTk99tj3-64gQaxuHpQKGk95Iyg

{
  "titulo": "Meu Primeiro Artigo!",
  "conteudo": "Este é o conteúdo do meu primeiro artigo, funcionou!",
  "usuarioId": "USR-0001",
  "categoriaId": 1
}

### 4. Postar um Comentário (MongoDB)
POST http://localhost:8080/comentarios
Content-Type: application/json

{
  "artigoId": "ART-2025-00001",
  "autor": "Leitor Anônimo",
  "texto": "Ótimo artigo, parabéns!"
}